repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/alan-turing-institute/CleverCSV-pre-commit
  rev: v0.8.2
  hooks:
  - id: clevercsv-standardize
